---
title: SMI 2020 - Course Introduction 
subtitle: ""
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc_depth: 3
---

```{r, echo = FALSE}
library(emo)
```

# Introduction

Welcome to the SISMID module **Infectious Diseases, Immunology and Within-Host Models**. On this website, we also use the title **Simulation Modeling in Immunology (SMI)**. You'll see us use it interchangeably. (That's because this website is planned to be a future resource not just for the SISMID course but more generally covering simulation modeling and immunology.)


# Course Setup
While this course is a module within SISMID, we use the term course or class for our module, and inside our course, there are specific modules covering certain topics. Those are listed under the _Modules_ menu. Within each module, there are one or several units. We will cover parts of most units during live Zoom sessions, other parts are meant for you to work through on your own.


* The _Schedule_ document gives a planned outline for the course. This is subject to change, so check the website and the Slack channel frequently.
* Each module consists of one or several units/documents containing a mix of writings or videos created by us or others, computer based exercises, discussions, etc. Content for a specific module is listed in the order you should go through things.  If anything is ever unclear, please ask (see _Communications_ section on course website).
* All material for the course can be accessed through this course website. We will update this page during the course, so keep refreshing every so often.
* The main page of the course describes the different sections and documents. 

# Course Tools
This is a brief overview of the tools we will be using. They are described in more detail in the other documents of this module.

* We will use the DSAIRM software package. This software is written for R. Therefore, you will also need to install R, which is very easy. Further instructions on this are provided.
* We will also use RStudio (a graphical frontend to R).
* We will use Slack for discussions, help, announcements, and any other form of asynchronous communication.
* We will use Zoom for synchronous components (i.e. lectures/discussions).

## Exercises
This course has a hands-on component, where you get to play around and explore models yourself. If applicable, the exercises part of the modules explain which exercises you can do for a given topic.

## Course project
If you want to challenge yourself and have the time and skills, you can try to do a small course project. The _Projects_ section provides more details.

## Discussion and Participation
We hope to get lively discussions going in our Slack workspace. Participate regularly!

# Course Resources
In this short course, we don't have time to go very deep into the various topics we discuss. To give you pointers for more information, we provide links to further resources both within materials for specific modules and in the _Resources_ section of the course website. 

# Getting help
Please use the communications tools for this class liberally to ask for help, clarification, etc. 
