---
title: Further tools 
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
output: 
  html_document:
    toc_depth: 3
---

**This reading is completely optional.**


# Overview
This is a very short unit with a few pointers to other tools and resources that might be of interest. We won't need them in this course, but some of you might decide to give them a try.

# modelbuilder
The DSAIRM package allows you to explore pre-written models. If you want to modify those models, you will have to get the underlying code and start editing it. This means you'll have to do some R coding. To allow individuals to build their own models without having to code, we started to develop the [modelbuilder](https://ahgroup.github.io/modelbuilder/) R package. It is in an early stage, but functional. If interested, you can give it a try and use it to build your own simulation model. You won't have to code. You will still need to ensure your model makes sense. _modelbuilder_ is not yet on CRAN, so you will have to install it from Github. The [_modelbuilder_ website](https://ahgroup.github.io/modelbuilder/) explains how.


# Github

Github is a very useful platform for working on projects, both those that mainly focus on coding and other types (e.g. data analysis, paper writing). Or hosting course materials, like the whole website for this course. It takes time to learn Github and we don't have the time in this course. But it might be of interest. If you are interested, check out [this introduction](https://andreashandel.github.io/MADAcourse/1d_Github.html) which I wrote for another online course I teach (and of course, feel free to browser through the whole course website if you have any interest in data analysis).


# Rmarkdown
Rmarkdown and its many variants (bookdown, blogdown, etc.) have become very powerful and versatile tools that let you write reports, papers, slides, websites (like this one), etc. all using a fairly easy format. I am currently using Rmarkdown for almost everything I write. For a brief introduction on Rmarkdown and the general concept of reproducible research (and how Rmarkdown fits into that), see e.g. [this introduction](https://andreashandel.github.io/MADAcourse/1e_ToolsforReproducibility.html), which comes from the same data analysis course as the Github writeup.




