---
title: SMI 2020 - Introduction to Immunology
subtitle: ""
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc_depth: 3
---

```{r, echo = FALSE}
library(emo)
```


# Overview
This document provides materials to give you a (VERY!) brief introduction to immunology.

# Learning Objectives
* Understand the major effector arms of the immune system
*  Describe the variation in pathogen “lifestyles” that must be handled by the immune response
* Distinguish innate and adaptive immunity
* Discuss the postulates of the clonal selection hypothesis and their subsequent validation

# Slides
We will go over an introduction to immunology in one of the zoom sessions. The slides for that session [can be found here.](./slides/Introduction_to_Immunology_Slides.pdf)

# Videos
The recordings of the lecture are broken into two segments. 

In the first segment, Paul covers innate immunity.

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/z3c4ZSmuTR0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>


In the second segment, he covers adaptive immunity.

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/d6IKOL-utNI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>




