---
title: Introduction to Modeling
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc_depth: 3
---

```{r, echo = FALSE}
library(emo)
```


# Overview
This module provides a brief introduction to simulation modeling.

# Learning Objectives
* Know what simulation modeling is.

# Slides
We will go over an introduction to modeling in one of the zoom sessions. 
There are two sets of slides. 
The first one giving a general introduction to modeling. You can get the slides here [as html](./slides/Introduction_to_Modeling_Slides.html) or [as pdf.](./slides/Introduction_to_Modeling_Slides.pdf)

The second one which discusses a few simple models. You can get the slides here [as html](./slides/Simple_Models_Slides.html) or [as pdf.](./slides/Simple_Models_Slides.pdf)

# Videos

The recordings of the lecture are available online, broken into two segments. 

The first segment provides a general introduction to simulation modeling.

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/BxSSU-uHjUQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>


The second segment goes in detail over a few very simple models.

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/sIYiFAfMH08" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>




# Reading

The other units in this module cover specific topics in some more detail.


# Further materials

Our recent review [Simulation Modelling for Immunologists](https://handelgroup.uga.edu/publication/2020-handel-natrevimm/) provides a general introduction to the kinds of simulation models we will be discussing in this course. If you haven't done yet, please read the paper. 

See the _Resources_ section for some additional materials, including a few textbooks, that cover within-host modeling. Some of the other readings in this module also have further pointers to additional material.
