---
title: Introduction to Modeling - Exercises
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc_depth: 3
---


# Overview

For the exercise portion of this module, you can explore and play around with the basic models you learned about. 
There are different ways you can do that, based on your level of comfort with both R code and models of that type. The different options are described below.

We recommend that no matter what your level is, you should at least briefly explore the models through the graphical interface and read the documentation for several of the models to get an idea of the overall setup of the package.


# Beginner

The easiest way to learn about these models is by using the graphical interface of DSAIRM. 

Explore the models listed in the __The Basic__ section of DSAIRM. You will find a model that describes a simple extracellular (bacteria) infection and one that describes a simple intracellular (virus) infection. A third model shows a more complicated version of a virus infection which includes several components of the immune response.

For each of the apps/models, go through all the tabs at the bottom of each app. __The Model__ and __What to do__ are the most important sections. If you are completely new to these kinds of models, work through all the listed tasks to get an idea of how these models work.


# Intermediate I

If you are not yet comfortable building your own models, but have some R coding familiarity, this might be a good option for you. If you want to have a bit more flexibility and are ok writing some R code, you can explore the models using the _Level 2_ approach described in the [DSAIRM tutorial](https://ahgroup.github.io/DSAIRM/articles/DSAIRM.html). You can still work through the tasks for each app, or do a more free exploration. In this version, you write your own little pieces of code to call the simulation models and explore the results. See the _Level 2_ description in the DSAIRM tutorial for more. 


# Intermediate II

If you have some familiarity with models of this type and want to go beyond the DSAIRM models, but are not comfortable writing R code, you can try to build your own model using the [_modelbuilder_](https://ahgroup.github.io/modelbuilder/) package. Using that package, you can build and explore your own models. It might be easiest to start with one of the provided example models and modify to your own needs.


# Advanced

If you have some familiarity with both simulation models and R coding, you have several options. You can start with a DSAIRM model, download its code and modify it to fit your own needs. An example of this approach is described under _Level 3_ in the DSAIRM tutorial. Another approach is to start with a model in [_modelbuilder_](https://ahgroup.github.io/modelbuilder/). You can build the basic model graphically, then export the code for it, and then run/explore the model or make further modifications to the code. Note that this is a "one way" approach. Once you exported code and make modifications, you (currently) can't load it back into _modelbuilder_. 

# Getting help

If at any point you are stuck, something is unclear, you want to discuss, etc. use our Slack Workspace.


