---
title: SMI 2020 - Complex Pathogen Life cycles and Immunology
subtitle: ""
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc_depth: 3
---

```{r, echo = FALSE}
library(emo)
```


# Overview
This document provides materials that discuss a few important larger pathogens, specifically TB and Malaria, and the immune response to those pathogens.

# Learning Objectives
* Understand the unique features of malaria and TB biology and their consequences for infection
* Compare and contrast immune effector mechanisms in acute vs. chronic infection settings
* Discuss aspects of pathogen biology that promote chronic infection or immune failure

# Slides
We will go over this topic in one of the zoom sessions. The slides for that session [can be found here.](./slides/Complex_Pathogens_Immunology_Slides.pdf)

# Videos
The recordings of the lecture are broken into two segments. 

In the first segment, Paul covers Malaria.

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/DJnoV2vV6Ik" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>


In the second segment, he covers Tuberculosis.

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/vka6fqSmXYk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>


