---
title: What influences model results
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc_depth: 3
---

```{r, echo = FALSE}
library(emo)
```


# Overview
This module describes some of the uncertainties that can affect outputs obtained from simulation models.

# Learning Objectives
* Know how different aspects of the model building and running process affect outcomes.
* Be familiar with approaches that allow one to quantify certain types of uncertainty.


# Slides
We will discuss this topic in one of the zoom sessions. You can get the slides here [as html](./slides/Uncertainty_in_Models_Slides.html) or [as pdf.](./slides/Uncertainty_in_Models_Slides.pdf)

# Videos

The recordings of the lecture are broken into three segments. 

The first segment discusses how model structure impacts outcomes.

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/RW-ZgTVT1fE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>


The second segment discusses parameter uncertainty and how to assess its impact.

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/xgPmDrz6uNQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>

The third segment discusses model stochasticity.

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/qfzeMYPr454" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>




# Reading
The other units in this module provide further information on specific topics. Note that there is some overlap between the slides and the reading.


# Further materials

Some of the other readings in this module have further pointers to additional material.
