---
title: What influences model results - Exercises
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc_depth: 3
---


# Overview

For the exercise portion of this module, you can explore and play around with the models in the _What influences model results_ section of DSAIRM. 


# Start

We recommend that no matter what your level is, you should at least briefly explore the models, read the documentation and attempt the suggested tasks by using the graphical interface of DSAIRM. 


# Continue

Once you explored the models, you can go in several directions, similar to the approaches suggested previously. 

If you want to further explore structural differences and how they impact model results, you could build several new alternative models (or a single one where you turn on/off parameters), either by editing some of the DSAIRM simulation functions (_Level 3_ approach) or by using the _modelbuilder_ package. 

If you want to explore stochastic models further, there is another app in DSAIRM, called _Influenza Antivirals and Drug Resistance_ which explores the use of stochastic models further. The _modelbuilder_ package also lets you build and analyze stochastic models, as well as export stochastic model code for further exploration. 

If you want to explore the uncertainty and sensitivity analysis topic further, you will need to get the code for that DSAIRM and modify the code. You can modify the code to call different underlying model functions, including new ones you might have built with _modelbuilder_, but you will need to modify the code that does the U/S analysis to match any new underlying model.  


# Getting help

If at any point you are stuck, something is unclear, you want to discuss, etc. use our Slack Workspace.


