---
title: SMI Course Glossary
subtitle: ""
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc: FALSE
---



```{r, echo = FALSE}
#just so I can use emoticons
#devtools::install_github("hadley/emo")
library(emo)
```

As in any field, there are lots of technical terms related to Modeling and Immunology. 
We try to explain them whenever they show up first. However, we figured it might also be useful to have one central place for quick reference. Terms are ordered alphabetically. This is how we define them, others might have slighlty different definitions.

This list is and will likely forever remain a work in progress and incomplete. If you think there is a specific term missing that should be listed and explained here, please let us know.

--- 


## Modeling related terms

__Agent Based Model (ABM):__ Also called individual-based models (IBM). A model in which individuals/agents are explicitly modeled. Agents can be entities such as hosts, virions, bacteria, cells, etc. Models are usually stochastic and have spatial structure (see also NetLogo). 

__AIC:__	An Information Criterion (often also called Akaike Information Criterion). A statistical measure that allows one to compare the goodness of fit of multiple models. Other quantities, such as BIC, DIC, Likelihood ratio, etc. can also be used for model selection.

__Compartment:__	Corresponds usually to a variable in a model, tracks the number of some variable in a certain stage. For instance the compartment/variable of cells in the infected state. 
Compartments track total numbers of a quantity, as opposed to agent-based model, where each unit is tracked individually (e.g. each infected cell is being modeled, instead of just modeling the compartment of the total number of infected cells). 

__Delay differential equation (DDE):__	A differential equation (or more often, a set of differential equations) that describe the dynamics of one or multiple quantities and allow for delayed actions. Example: The influx of new cells into a system could depend on the number of cells several hours/days ago. 

__Discrete time model:__	A mathematical model in which one or multiple variables are updated in discrete time-steps. Contrast this with differential equation models, which implement continuous-time dynamics. 

__Deterministic:__	A system that – for a given set of initial conditions and parameters – produces always the same dynamics/outcome

__Dynamic model:__	A model that tracks how entities change as a function of time. 

__Fitting/Inference:__	The rigorous, statistical comparison of a (mechanistic or phenomenological) model with data. This is used to test hypotheses and estimate parameters.

__Initial condition:__	The state of the system (i.e. the values of the different variables of a system) at the beginning (usually at the start of the infection, or at the start of treatment, etc.). Needs to be specified to allow simulating a model.

__Mechanistic model:__	A model that explicitly describes processes/mechanisms of a system, either in terms of mathematical equations or computer instructions.

__Parameter:__ A quantity of a model that is usually considered fixed. For instance the life-span of an infected cell is a parameter. Parameter values are needed to fully specify a system. They can be obtained from experimental data, either through reading the literature or through fitting of models to data.

__Phenomenological model:__	A model that captures correlations between certain quantities without invoking specific mechanisms. Most statistical models fall into this category.

__Ordinary differential equation (ODE):__	A differential equation (or more often, a set of differential equations) that describe the continuous-time dynamics of one or multiple quantities/variables. The left-hand side of the equation specifies the quantity/variable; the instantaneous change is specified on the right-hand side of the equation. 

__Quantitative model:__	A mathematical or computational description of some system of interest.

__R:__	Freely available programming language that allows for relatively easy and convenient implementation of a large number of statistical and scientific research projects. 

__Spatial model:__	A model that in some way explicitly accounts for spatial structure. Most ABM are spatial models, compartmental models can include spatial features.

__Statistical Learning:__ A term that seems to become more widely used in recent years. While some people distinguish this term from __Statistics__ and consider it a sub-field, the two terms are often used interchangably.

__Statistics:__ The basic/classical machinery for data analysis. Depending on the type of data, many different approaches have been developed (parametric vs. non-parametric methods, longitudinal analysis, time-series analysis, and many more). Models tend to be simple and interpretable, the goal is to understand how inputs (predictors) relate to outcomes. Statistics was developed when data was sparse, computers didn't exist, and mainly scientists interested in a deep understanding of their data used it. Because of this, statistical models tend to be simple and work well on small datasets. 

__Stochastic:__	A system that can produce varying dynamics/outcomes when simulated multiple times, even for a given set of initial conditions and parameters. 

__Uncertainty/Sensitivity analysis:__	An approach in modeling that helps one to understand how uncertain model outcomes are, given uncertainty in the inputs. It also allows one to figure out how much of the outcome uncertainty can be attributed to specific inputs. Inputs are often parameters, but don’t have to be.

__Variable:__ Any quantity that we consider to change (i.e. be variable). Almost always the change is over time. This change is tracked with some equation or model (e.g. an ODE, DDE, ABM). Contrast that to __Parameter__. 

__Mechanistic Modeling:__ Building and using models that explicitly incorporate mechanisms and processes of the system under study to understand _how_ things interact and lead to specific outcomes. Many models in the hard sciences are of this type. A common way to formulate such models is with differential equations.


## Immunology related terms

_Partly adapted from “An Interpretative Introduction to the Immune System??? by Steven Hofmeyr in Design Principles for the Immune System and Other Distributed Autonomous Systems ed. Segel and Cohen._

__Adaptive immune system:__	That part of the immune system that uses antigen receptors and adapts or “learns??? to recognize specific antigens, and retains a memory of those antigens to enhance future responses

__Affinity maturation:__	Darwinian process of variation and selection that occurs to B cell receptors in lymph nodes and spleen, leading to the evolution of B cell populations better adapted to recognize specific epitopes

__Antibody:__	A soluble form of B cell receptors secreted by plasma B cells, with multiple anti-pathogen effector functions

__Antigen:__	Originally, any substance that causes the production of antibodies; now, more generally, anything that is recognized by antibodies or by the antigen receptors of lymphocytes

__Antigen processing:__	The process whereby antigen-presenting cells (such as B cells, dendritic cells and macrophages) engulf antigens, digest them, and present fragments of their proteins MHC/peptide complexes

__Apoptosis:__	Programmed cell death

__B cells:__	Lymphocytes that mature in the bone marrow and secrete antibody

__CD4:__	Cell surface molecule often used to identify T-helper lymphocytes, a co-receptor for the TCR complex, binding Class II MHC

__CD8:__	Cell surface molecule often used to identify cytotoxic T lymphocytes, a co-receptor for the TCR complex, binding Class I MHC

__Cellular response:__	A historical term, now used to refer to the part of the immune response that is connected with T cells

__Central tolerance:__	Process of tolerizing immature T cells in the thymus

__Chemokines:__	Soluble signal molecules that direct cell trafficking

__Class I MHC:__	MHC, which occurs in almost all cells, that primarily presents (in an “MHC/peptide complex???) peptides generated in the cell’s interior

__Class II MHC:__	MHC, which only occurs in certain cells of the immune system or when particular cells are activated that mostly presents fragments of proteins that are bound to the cell surface or that have been ingested

__Clonal deletion:__	Process whereby immature T cells that strongly recognize a self antigen in the thymus die by apoptosis

__Cluster of Differentiation (CD):__	System of nomenclature for classifying cell surface proteins on white blood cells, usually identified by monoclonal antibodies—over 350 “CD antigens??? are currently described

__Complement:__	Molecules that participate in the immune response by binding to bound antibodies or certain microbial products, often culminating in cell or pathogen permeabilization

__Costimulation:__	The mechanism whereby two or more signals participate in the process of activating a lymphocyte

__Cross-presentation:__	An alternate pathway of Class I presentation that directs peptides derived from ingested proteins normally directed to Class II presentation into the Class I MHC presentation compartment; associated with professional antigen-presenting cells

__Cytokines:__	Signal molecules that transmit information between cells

__Cytotoxic T cells:__	T cells that are activated to kill target cells, usually CD8+

__Dendritic cells:__	Professional antigen presenting cells, generally considered to be the most potent activators of naïve T cells and required for the initiation of primary responses

__Endocytosis:__	The process by which cells engulf extracellular material, usually bound to their surface by a receptor. After endocytosis, the material is contained with a cytoplasmic structure called an endosome

__Epitopes:__	An MHC/peptide complex or specific region of an antigen to which an antigen receptor (TCR, BCR) binds

__Humoral response:__	A historical term for immune responses involving mainly B cells and their antibodies

__Hypermutation:__	Mutation at the junctional or hypervariable regions of antigen receptors, typically occurring during affinity maturation

__Immunodominance:__	The differential expansion of subsets of the potential epitope-specific lymphocyte responses in response to complex antigens

__Innate immune system:__	That part of the immune system that depends on germline encoded receptors; it generally does not change or adapt to specific pathogens

__Inoculum:__	Usually, the microorganism or biological material given to an individual as a vaccination in order to stimulate a specific immune response

__Interferons:__	Types of cytokines originally discovered because of their anti-viral action

__Isotypes:__	The several structural varieties of the constant regions of antibodies. Isotypes include IgM, IgG (including multiple subtypes), IgA and IgE

__ID50:__	Infectious Dose 50, the dose of a pathogen minimally required to infect 50% of a culture, population of organisms etc. Similarly, LD50 is a dose required to kill 50% of a population

__Leukocytes:__	White blood cells, including lymphocytes, neutrophils, eosinophils, basophils, monocytes and macrophages

__Lymph nodes:__	Small organs, distributed throughout the body, in which an adaptive immune response can develop

__Lymphocytes:__	T cells and B cells

__Macrophages:__	Scavenger cells the engulf pathogens, process antigens and signal to other arms of the immune system. Macrophages also have many direct anti-pathogen effector functions

__Major histocompatibility complex (MHC):__	The cell surface molecules that restrict T cell receptor recognition. Two classes of these molecules present self and foreign peptide antigen which are then recognized by TCR. Important in self/non-self determination

__Memory cells:__	Lymphocytes that have been activated in the past and retain a memory of previous antigens, engendering a secondary response to future contact with the antigen

__Natural Killer cells:__	Cells of the innate immune system that kill tumor cells and intracellular pathogens, recognizing them by alterations in cell surface protein expression

__Negative selection:__	The process of clonal deletion used to eliminate autoreactive T cells in the thymus

__Neutralization:__	The process whereby antibodies binding to pathogens prevent binding between the pathogen and its receptors on host cells

__Opsonization:__	The coating of cells with complement or antibodies, leading to phagocytosis

__Pathogens:__	Microorganisms such as bacteria, parasites, viruses and fungi that invade the body and cause illness

__Peptides:__	Protein fragments

__Peripheral tolerance:__	Mechanisms that occur in individual, autoreactive lymphocytes that have escaped central tolerance to become non-functional or undergo apoptosis, preventing autoimmunity

__Phagocytes:__	Professional antigen presenting cells that engulf debris, pathogens and other cells (include macrophages and dendritic cells)

__Pharmacokinetics:__	The study of the fate of substances administered externally to an organism, usually drugs, including liberation, absorption, metabolism, distribution and excretion 

__Pharmacodynamics:__	The study of the physiological effects of drugs on the body

__Plasma cells:__	Activated B cells that secrete antibodies

__Plaque Forming Units (PFU):__	A measure of viral titer, performed by observing the localized growth of individual viruses which lyse their target cells creating a “plaque???. 

__Positive selection:__	The stimulation and maturation in the thymus of T cells with sufficient affinity to antigens presented by self MHC; T cells that do not undergo positive selection in the thymus die by apoptosis

__Primary response:__	The immune response to antigens that the immune system has never before encountered

__Red blood cell (RBC):__	Also erythrocyte; the most abundant blood cell, responsible for transporting oxygen throughout the organism

__Regulatory T cell:__	A type of CD4 T helper cell that regulates and suppresses effector responses, limiting immune-associated pathology

__Repertoire:__	The diversity of lymphocyte receptors present in the immune system

__Secondary response:__	The memory-based immune response to antigens that the body has previously encountered

__Signal I:__	A necessary signal for activating a lymphocyte, typically provided by the binding of antigen receptors to an antigen epitope

__Signal II:__	A second signal required for activating a lymphocyte, typically provided by an activation-induced cell surface molecule on the antigen-presenting cell

__Th1:__	A differentiation state of T helper cells characterized by specific cytokines (including IFN-γ) and associated with cytotoxic T cell activation and the elimination of intracellular pathogens

__Th2:__	A differentiation state of T helper cells characterized by specific cytokines (including IL-4, IL-5 and IL-13) and associated with humoral responses and the elimination of extracellular pathogens, but also mediate allergy and asthmatic responses

__Th17:__ 	A differentiation state of T helper cells characterized by specific cytokines (including IL-17 and IL-22) and associated with anti-microbial immunity at mucosal and epithelial surfaces, but also likely play an important role in autoimmune responses 

__T cell receptor (TCR):__	The variable antigen receptor on T lymphocytes, generated by V(D)J recombination and restricted by binding to MHC

__VDJ recombination:__ Variable, Diversity, Joining recombination, the process by which B and T cell receptors are generated by semi-random recombination of the genomic DNA to create the broad diversity of the immune receptor repertoire
