---
title: Simulation Modeling in Immunology - Course Schedule
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc: FALSE
---

This is the current course schedule for the class. Things might change, so check regularly for updates.

## Notes

**Time zones:** Seattle is in the PT zone. Your instructors are in ET (Andreas) and CT (Paul) zones. Some of you are likely in yet other locations and time zones. We hope we can keep things straight. For any times in this course **we plan to use PT/Seattle time as reference.** We also plan to be clear when posting any time by stating the time zone explicitly. If ever in doubt, i.e. if you see us posting a time without specifying the zone, please tell us to clarify. 

For details on Slack and Zoom use, see the __Communication__ section.

Abbreviations used: [DSAIRM = Dynamical Systems Approach to Immune Response Modeling - R package](https://ahgroup.github.io/DSAIRM/). Numbers refer to the number of the app. 

***


## Before course start

* Familiarize yourself with this website. Read through all pages apart from the ones under the _Modules_ tab.
* Go through the materials listed under _Module 1_. You should end up with R/Rstudio up and running and the DSAIRM package installed and working. 
* Read [Simulation Modelling for Immunologists](https://handelgroup.uga.edu/publication/2020-handel-natrevimm/).


## Monday 2020-07-20

8 - 9 PT (10CT/11ET) - Zoom: Welcome and introduction 

_break_

9.30 - 10.30 PT (11.30CT/12.30ET) - Zoom: Introduction to Immunology 

_break_

11 - 12 PT (1CT/2ET) - Zoom: Introduction to Modeling 

12 - 2 PT - On your own: Go through module 3 content, practice as described in the _Exercises_ section. Communication through Slack.  

2 - 2.30 PT (4CT/5ET) - Zoom: Discussion, Q&A

Rest of day - On your own: More DSAIRM/modeling practice. Communication through Slack.  

***

## Tuesday 2020-07-21

8 - 9 PT (10CT/11ET) - Zoom: Virus Infections and Immunology

_break_

9.30 - 10.30 PT (11.30CT/12.30ET) - Zoom: How to use models

10.30 - 12 PT - On your own: Go through module 5 content, practice as described in the _Exercises_ section. Communication through Slack.  

12-1 PT (2CT/3ET) – Zoom: Complex Pathogen Life cycles and Immunology (TB and Malaria)

_break_

1.30-2.30 PT (3.30CT/4.30ET) - Zoom: What influences model results. Followed by daily discussion/Q&A.

Rest of day - On your own: Go through module 7 content, practice as described in the _Exercises_ section. Communication through Slack.  

***

## Wednesday 2020-07-22

8 - 9 PT (10CT/11ET) - On your own: modeling practice.

9 - 10.30 PT (11CT/12ET) - Zoom: Further topics based on request, final Q&A and wrap-up. 

Rest of day - On your own: Continued modeling practice. Communication through Slack.  

***

## Any time

Go through module 8 content.

***


## After course end

* This course website will remain online. 
* DSAIRM and modelbuilder packages will continue to be available.
* We will keep the Slack workspace open for at least several more weeks (but might be slower to respond). Feel free to keep using it. I'll post a note to the Slack workspace before I shut it down. If you want to continue communications with us or fellow classmates after that, we suggest you switch to other means (e.g. email).

