---
title: SMI Course Resources
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
output: 
  html_document:
    toc_depth: 3
---


```{r, echo = FALSE}
#just so I can use emoticons
#devtools::install_github("hadley/emo")
library(emo)
```

This page lists resources that are explicitly used or mentioned in this course. For a more extensive list of resources, see the _General Resources_ page.

All materials described below are (should be) freely available online. If you can't get to them, let me know. Note that a lot of the listed resources are dynamic and ever changing. That means occasionally links might not work, sites go offline, chapters in online books get re-arranged, etc. If you notice anything that's not quite right, please let me know.

**Note: Several of the papers we reference might be behind a paywall. You can find a link to a zip file that contains most (all?) references in course Slack workspace. Let us know if you have trouble downloading that zip file or if any references are missing.**

# General help

* The main place to get any course specific help are the various Slack channels in our course workspace. Use them widely to ask questions, to answer others' questions, to post links to interesting resources, etc. 
* There will very likely be times when some material in the course doesn't quite make sense and you need to do some auxiliary reading. Google will be your best friend. Wikipedia is often a very good starting point for many topics. 



# Review Papers

* [Simulation Modelling for Immunologists](https://handelgroup.uga.edu/publication/2020-handel-natrevimm/). A review/introduction we wrote on the topic. You will see a lot of overlap between that paper and the course materials. Read the paper before the course, then maybe re-read a few more times during the course.
* The paper [Modelling Viral and Immune System Dynamics](https://www.nature.com/articles/nri700) by Alan Perelson is another nice introduction focusing on virus models and explaining a few different models. 
* The paper [The role of models in understanding CD8+ T-cell memory](https://www.nature.com/articles/nri1550) by Antia et al. introduces a few simple models for T-cell dynamics.



# Hands-on/interactive resources

* [Dynamical Systems Approach to Immune Response Modeling (DSAIRM)](https://ahgroup.github.io/DSAIRM/). The R package was written for this course and allows you to engage in hands-on explorations of the different topics we will cover.

* [modelbuilder](https://ahgroup.github.io/modelbuilder/). An R package that allows you to build and analyze your own models without having to write code. This is optional, we won't formally use it in the course but you might want to explore it on your own. Note that the package is work in progress (feel free to contribute `r emo::ji('smiley')`).



