---
title: General Infectious Disease Epidemiology and Modeling Resources
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc_depth: 3
---


```{r, echo = FALSE}
#just so I can use emoticons
#devtools::install_github("hadley/emo")
library(emo)
```

To distinguish clearly which external resources are directly related to the course and which are not, we decided to have two resource pages. The _Course Resources_ page lists materials directly related to and used/mentioned in the course. This page lists other resources that might not be used or mentioned explicitly in the course, but that might be useful and interesting. 

Apart from the books, most other materials described below are (should be) freely available online. For better or for worse, a lot of the resources I list below are dynamic and ever changing. That means occasionally links might not work, sites go offline, chapters in online books get re-arranged, etc. If any link does not work and you can't access the materials for some reason, let me know so I can update this document.

_Let me know if you find other relevant and good resources that you think could be listed here._


# Within-host simulation modeling books

_There isn't really a textbook that teaches simulation modeling which is both comprehensive and suitable for beginners. The following books cover some aspects of within-host modeling and might be suitable for some learners._

* [Nowak and May (2001). "Virus Dynamics: Mathematical Principles of Immunology and Virology."](https://amzn.to/3fwonRj) - Mostly a collection of work done by the authors, published in book form. Somewhat outdated and quite expensive. Probably not worth buying unless you find it somewhere cheap, you can instead look for their original papers. 
* [Wodarz (2007). "Killer Cell Dynamics - Mathematical and Computational Approaches to Immunology."](https://amzn.to/2WjJQFS) - a nice overview of some work by the author and others on modeling T-cells. A bit outdated and kinda expensive. I would first check it out from the library before deciding if you want to buy it.  
* [Esteban A. Hernandez-Vargas (2019). "Modeling and Control of Infectious Diseases in the Host"](https://amzn.to/2Ooth7j) - The most comprehensive of the books in terms of topic coverage. Technically advanced, mainly suitable for individuals with strong quantitative backgrounds (engineering, physics, math, etc.) who want to learn about within-host modeling. 


# Immunology books

* [How the Immune System works](https://amzn.to/3ev68dO) - a nice introduction to the immune system, focusing on the big picture. Good for those who are new to immunology.
* [Janeway's Immunobiology](https://amzn.to/2Wlmsrr) - a very comprehensive immunology textbook.
* [Basic Immunology](https://amzn.to/30yjXmJ) - another comprehensive immunology textbook.



# Other books

The types of simulation models we discuss in this course are common in other areas of science. The study of infectious diseases on the population level (i.e. epidemiology/ecology/evolution) has a long history of using these kinds of models. There are a number of good resources dedicated to models on the population level. Most of the ideas and concepts apply directly to the within-host level. For a list of resources with a focus on population-level infectious diseases and modeling, check out the _Resources_ sections of my online course [Infectious Disease Epidemiology
- A model-based approach (IDEMA)](https://andreashandel.github.io/IDEMAcourse/). Note that the overall course website is currently under construction and there are likely parts that don't work.

# Journal articles

* Perelson (2002). Modelling Viral and Immune System Dynamics. Nature Reviews Immunology.
* Antia et al (2005). The role of models in understanding CD8+ T-cell memory. Nature Reviews Immunology.



# Lists and other sources

* I created lists related to R and Data Analysis (as well as other topics). [You can find all resource lists here](https://andreashandel.github.io/research-and-teaching-resources/). (These lists are works in progress, and some are better/more useful than others. Feel free to send me links/resources to include).


