---
title: Introduction to Modeling
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/SMICourse.bib
output: 
  html_document:
    toc_depth: 3
---

```{r, echo = FALSE}
library(emo)
```


# Overview
This module provides a brief introduction to simulation modeling.

# Learning Objectives
* Know what simulation modeling is.


# Videos & Slides

These videos are lecture recordings from SISMID 2020. They are broken into two segments. 

The first segment provides a general introduction to simulation modeling. You can get the slides for the first lecture here [as html](./slides/Introduction_to_Modeling_Slides.html) or [as pdf.](./slides/Introduction_to_Modeling_Slides.pdf)

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/BxSSU-uHjUQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>


The second segment discusses a few very simple models. You can get the slides here [as html](./slides/Simple_Models_Slides.html) or [as pdf.](./slides/Simple_Models_Slides.pdf)

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/sIYiFAfMH08" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>


The following video from 2021 is a very brief overview of the main points covered in the previous two lectures, followed by questions and answers. It is recommended you watch this video after the first two. The slides from this short presentation are here [as html](./slides/2021_Intro_to_Modeling_Discussion_Slides.html) or [as pdf.](./slides/2021_Intro_to_Modeling_Discussion_Slides.pdf).  

<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/mNrE-L9Er0I" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>



# Reading

The other units in this module cover specific topics in some more detail.


# Further materials

Our recent review [Simulation Modelling for Immunologists](https://handelgroup.uga.edu/publication/2020-handel-natrevimm/) provides a general introduction to the kinds of simulation models we will be discussing in this course. If you haven't done yet, please read the paper. 

See the _Resources_ section for some additional materials, including a few textbooks, that cover within-host modeling. Some of the other readings in this module also have further pointers to additional material.
