---
title: Model and Systems Thinking
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
bibliography: ./media/SMICourse.bib
output: 
  html_document:
    toc_depth: 3
---

```{r, echo = FALSE}
library(emo)
```


# Overview 
Here we discuss briefly the overall idea of taking a model perspective, sometimes also called interchangeably a _systems_ perspective, and how it is applied to immune response modeling.


# Learning Objectives
* Understand the basic ideas of complex systems and systems thinking/modeling
* Assess strength and weaknesses of different modeling approaches
* Know the difference between phenomenological and mechanistic models




# Systems or Model Thinking
The scientific approach that has generally been the most successful in the past was to break down a system into its components and study the components one at a time. Usually referred to as the *reductionistic approach*. This approach to understanding the world is still very powerful and useful. 

A complementary approach, which has seen increased use, is to look at "the whole" system at once, instead of each component at a time. Using the whole system approach can provide insights that might not be obtained by the purely reductionist approach. Looking at the whole system at once is often referred to as _systems thinking/approach_.

The term _systems thinking_ or _systems approach_ or similar such terminology has become popular in various fields during the last few decades. It is not a very clearly defined term, but in general, a _systems_ perspective looks at multiple - often many - components that interact with each other in potentially complicated ways. Since models are an indispensable tool to study system of interacting components, the term _model thinking_ is also sometimes used. More generally a systems perspective and the use of models generally go together.

In the context of within-host infection and immunology, the system is the complex interactions of pathogen, host, and possibly environment, that determine the process and outcome of an infection. Since infections unfold over time, we usually want to study the _dynamics_ of our system. This leads us to a _dynamical systems perspective_. Specific types of models, called _mechanistic models_ are especially well suited to describe dynamical systems and are therefore the primary choice for the study of complex dynamical systems. We describe them next.



# Models
Models are everywhere in science. Models can be conceptual (e.g. graphs or charts), experimental model systems (e.g. a specific mouse strain in immunology) or take the form of mathematical/computer models. The terms 'model' and 'modeling' are widely used and have no clearly defined meaning. We start by defining and distinguishing between 2 broad categories of models and then focus in the following on one of them. 

Once we take the systems perspective, we have to deal with many components that interact in potentially complicated ways. Making study and analysis complicated, especially if we are trying to gain insights into the causal and mechanistic connections between some quantity (exposure) and some outcome. When taking a systems approach, it is therefore often not enough to have a conceptual model alone. While a conceptual approach often allows some qualitative understanding, it is somewhat limiting. It is for instance almost impossible to gain a good *quantitative* understanding how changes in certain conditions and components of a system lead to changes in outcomes of interest by relying on conceptual approaches alone. If we want to go beyond qualitative and move toward a quantitative understanding, we need mathematical/computational models. There are many different types of models one can implement. The following categorizes and defines two major types of modeling approaches. In this couse, we will focus on the second type of models.


## Phenomenological Models
A huge class of models consists of what we usually refer to as statistical models. In the context of this discussion, I prefer to label them _phenomenological_ models, but that terminology is rarely used. The idea behind the phenomenological approach is to build a parsimonious mathematical or computational model and use statistical approaches to compare the model with the data and to determine if there are any patterns in the data. 

For instance, a linear regression model investigates if there is a pattern/correlation between some input(s) and output(s) of interest that can be well approximated by a linear function. More complicated statistical models exist, some go by the name of _machine learning methods_. All of these models try to determine if there are patterns between inputs and outputs of interest in the data. Statistical methodology can then be used to determine if any observed pattern is "real" or might be due to chance. The simple t-test is an example.

These phenomenological models do not try to describe the mechanisms by which patterns might arise. For instance, if we find that the number of T-cells at the peak of an infection correlates linearly with the number of epitope-specific naive T-cells, we can't conclude for certain that the precursor number of T-cells is the cause of different peak T-cells (though it is a reasonable assumption). We also do not know what processes and mechanisms lead from naive T-cells to activated T-cells.

This non-mechanistic, phebomenological approach is both a strength and a weakness. With this approach, we can find patterns (e.g. correlations) in data without having to be able to postulate mechanistically how those patterns arise. On the flip side, these phenomenological models also provide little insight regarding potential mechanisms. If we want to explicitly study mechanisms and processes using models, we need to use _mechanistic_ models, described next.



## Mechanistic Models
As the name suggests, mechanistic models try to explicitly model the mechanisms leading to observed patterns for a given systen under study. Usually, the models are a highly simplified - but done well, still very powerful - abstraction of the system under study. The advantage of these kinds of models is that they potentially provide mechanistic insights, leading to a better and deeper understanding of the system. The main disadvantage is that we already need to know (or at least assume) a good bit about how the components interact for us to be able to build such a model. If we don't know enough to even postulate potential mechanisms underlying the observed data, we can't build a mechanistic model.

Mechanistic models are generally evaluated with computer simulations, thus in this course we mostly refer to them as simulation models. While this terminology is a bit fuzzy (e.g. complex statistical/phenomenological models often also rely on simluations), for the purpose of this course all our models are mechanistic simulation models and we use either term.

Both phenomenological and mechanistic models are useful tools with distinct advantages and disadvantages. Deciding which one to use depends on the question and study system. Here, we will focus our discussion on mechanistic models. Since the most common type of mechanistic model in the context of within-host modeling are ordinary differential equation based models, we will focus on those, with a brief mention of other mechanistic modeling approaches.


# History of mechanistic within-host models
Early mechanistic models for the immune response, with a focus on B-cells, were developed in the 70s (see e.g. [@bell70; @bell71; @bell71a]). 
An early, semi-mechanistic model to describe influenza infections was developed in [@larson76].
The use of such mechanistic models to study infection and immune responses dynamics continued to slowly increase during the 70s and 80s, and really took off in the 90s. Mechanistic models played an important role in understanding HIV infection dynamics and treatment [@ho95; @perelson96], and have since been applied to many other infectious diseases such as HCV [@neumann98], malaria [@mideo08c], tuberculosis [@wigginton01] and many others.



# Further Resources
* The paper "Why Model?" by Joshua Epstein [@epstein08] provides a nice, short discussion of the purposes of models. Other general introductory discussions of systems thinking and model use are [@may04; @chubb10; @garnett11; @basu13; @gunawardena14; @homer06; @peters14; @sterman06].


# References

