---
title: Multi-scale models
subtitle: ""
author: Andreas Handel
institute: "University of Georgia"
date: "`r file.mtime(knitr::current_input())`"
bibliography: ./media/SMICourse.bib
output: 
  html_document:
    toc_depth: 3
---

```{r, echo = FALSE}
library(emo)
```


# Overview
This document provides a brief, non-exhaustive introduction to models that connect the within-host (immunology) and between-host (epidemiology) scales.

# Learning Objectives
* Know what multi-scale models are.
* Decide when a multi-scale model might be useful.


# Introduction 
Infectious diseases operate on different temporal and spatial scales. Processes inside a host or pathogen cell might be on sub-militer scales and happen in second, processes on the population level might span the globe and can unfold over many years. In between are multiple additional scales. We will briefly discuss how models can connect two scales, namely the within-host level and the population level. 


# Interactions across scales


# Simple example models

It is easiest to discuss multi-scale models in the context of an example. Let's consider spread of an acute viral infection (e.g. influenza) at the within-host and the population level. At the within host level, we can start with the basic virus model.


$$
\begin{aligned}
\dot{U} & =  n - d_UU - bUV \\
\dot{I} & =  bUV - d_I I \\     
\dot{V} & =  pI - d_V V -  gb UV \\
\end{aligned}
$$

At the population level, we'll look at the standard SIR model, with compartments being susceptible, infected and infectious, and recovered. To avoid confusion, we give all the parameters on the population level model Greek letters.

$$
\begin{aligned}
\dot S & = \nu - \beta SI - \mu S  \\ 
\dot I & = \beta S I - \gamma I - \mu I \\
\dot R & = \gamma I  - \mu R  \\
\end{aligned}
$$

The two models might be linked in various ways. For instance it would be reasonable to assume that the rate of infection on the population level depends on within-host virus load. To keep it simple, we can assume a linear relation, i.e. $\beta = kV$, with $k$ some parameter.


# Example question
How do fitness on the within-host level and fitness on the between-host level compete? Fitness is a difficult concept to define and there is no single right way. An often-used approach is by looking at the reproductive number, which is the average number of new entities (new virus particles, new infected hosts) produced by one of them (one virion, one new infected host). Note that this can be an indirect process, e.g. a virion produces more virions by infecting a cell. 

We won't go into the details of how R0 is derived, just state that for the two models above, we have $R_w=\frac{bU_0p}{d_I(d_V + gbU_0)}$ for the within-host fitness of the virus and $R_b = \frac{bS_0}{g+m}$ for the between-host fitness.


If the between-host parameters are independent of the within-host parameters, a virus can maximize its overall fitness by independently increasing $R_w$ and $R_b$. There 
But parameters are unlikely to be independent. What possible connections can you think of? 



# Closing the loop




# Additional reading




# References


Gilchrist and Cooms (2006) Theoretical Population Biology, Coombs, Gilchrist and Ball (2007) Theoretical Population Biology
A recent review of the (sparse) work in that area: Mideo, Alizon and Day (2008) Trends in Ecology and Evolution
A focus on several within-host scales: Young, Stark and Kirschner (2008) Nature Reviews Microbiology
